# Generated by Django 5.0.7 on 2024-08-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_code', models.CharField(max_length=10, unique=True)),
                ('arrived_at', models.DateTimeField()),
                ('left_at', models.DateTimeField()),
            ],
        ),
    ]
