# Generated by Django 5.0.7 on 2024-08-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='arrived_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='left_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
