# Generated by Django 5.0.7 on 2024-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0002_alter_plate_arrived_at_alter_plate_left_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
