# Generated by Django 5.0.7 on 2024-08-27 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0003_alter_plate_left_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatePaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plate_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plates.plate')),
            ],
        ),
    ]
