# Generated by Django 5.0.7 on 2024-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0004_platepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platepaid',
            name='plate_code',
            field=models.CharField(max_length=10),
        ),
    ]
